version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: echo ToDo Build Docker image.
      - run:
          name: Publish Docker image to Docker Hub
          command: echo ToDo Publish Docker image to Docker Hub.
